dblp:
  url: https://dblp.org/search/publ/api?q={}&format=json&h=1000
  keyword: federate
  queries:
    - "venue:IJCAI:"
    - "venue:AAAI:"
    - "venue:AISTATS:"
    - "streamid:conf/alt:"
    - "streamid:journals/ai:"
    - "venue:NeurIPS:"
    - "venue:ICML:"
    - "venue:ICLR:"
    - "venue:COLT:"
    - "venue:UAI:"
    - "streamid:journals/ml:"
    - "streamid:journals/jmlr:"
    - "streamid:journals/pami:"
    - "venue:KDD:"
    - "venue:WSDM:"
    - "streamid:conf/sp:"
    - "venue:CCS:"
    - "streamid:conf/uss:"
    - "venue:NDSS:"
    - "venue:CVPR:"
    - "venue:ICCV:"
    - "venue:ECCV:"
    - "streamid:conf/mm:"
    - "streamid:journals/ijcv:"
    - "venue:ACL:"
    - "venue:NAACL-HLT:"
    - "venue:EMNLP:"
    - "venue:COLING:"
    - "venue:SIGIR:"
    - "streamid:conf/sigmod:"
    - "venue:ICDE:"
    - "streamid:journals/pvldb:"
    - "venue:SIGCOMM:"
    - "venue:INFOCOM:"
    - "venue:MobiCom:"
    - "venue:NSDI:"
    - "venue:WWW:"
    - "venue:OSDI:"
    - "venue:SOSP:"
    - "venue:ISCA:"
    - "venue:MLSys:"
    - "streamid:conf/eurosys:"
    - "streamid:journals/tpds:"
    - "venue:DAC:"
    - "streamid:journals/tocs:"
    - "streamid:journals/tos:"
    - "streamid:journals/tcad:"
    - "streamid:journals/tc:"
    - "streamid:conf/icse:"
    - "streamid:journals/focs:"
    - "streamid:conf/stoc:"
  mails:
    - "im.young@foxmail.com"
